#pragma once

namespace MONSTER {
	enum E_TYPE { TYPE_NORMAL, TYPE_BOSS, TYPE_END };
}

namespace OBJ {
	enum E_TYPE { TYPE_PLAYER, TYPE_ENEMY, TYPE_BULLET, TYPE_END };
}

namespace ITEM {
	enum E_TYPE { TYPE_NONE, TYPE_POWER, TYPE_MAX_POWER, TYPE_BUDDY, TYPE_END };
}

namespace ATTACK_PATTERN {
	enum E_PATTERN { 
		PATTERN_NORMAL, PATTERN_NORMAL_TARGET, PATTERN_DOUBLE, PATTERN_DOUBLE_TARGET, PATTERN_FAN, PATTERN_FAN_TARGET, 
		PATTERN_TORNADO, PATTERN_SJH_BOSS_ATTACK, PATTERN_ZD_BOSS_ATTACK,	// 0-8
		PATTERN_END };
}

namespace PLANE {
	enum E_AFFILIATION { AFFILIATION_LEADER, AFFILIATION_DEPENDENT, AFFILIATION_NONE, AFFILIATION_END };
	enum E_STATE { STATE_IDLE, STATE_ATTACK, STATE_DEAD, STATE_DEADSIX, STATE_EVASION, STATE_END };
}

namespace ENEMY {
	enum E_TYPE { TYPE_TANK, TYPE_PLANE, TYPE_FRIGATE, TYPE_CARRIERSHIP, TYPE_END };
}

enum STAGE { STAGE1, STAGE2, STAGE3, BOSS, ENDING, END_STAGE };