#pragma once

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	// ID_DYNAMIC : 실시간 업데이트가 필요한 컴포넌트
	enum COMPONENTID	{ ID_DYNAMIC, ID_STATIC, ID_END };
	enum INFO			{ INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION		{ ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum RESOURCETYPE	{ RESOURCE_STATIC, RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_END	};

	enum BUFFERID {
		BUFFER_TRICOL, BUFFER_RCCOL, BUFFER_RCTEX, BUFFER_RCXZTEX,
		BUFFER_CAPSULECROSSTEX, BUFFER_PLANETEX, BUFFER_TERRETTEX,
		BUFFER_CYLINDER, BUFFER_CIRCLE, BUFFER_MESHTEX, BUFFER_TERRAINTEX,
		BUFFER_CUBETEX, BUFFER_NAVITRICOL
	};
	enum TEXTURETYPE	{ TEX_NORMAL, TEX_CUBE, TEX_END };
	
	enum RENDERID		{ RENDER_PRIORITY, RENDER_SHADOWDEPTH, RENDER_NONALPHA, RENDER_NONALPHA_SHADER, RENDER_NONALPHA_OUTLINE, RENDER_GLASS, RENDER_ALPHA, RENDER_UI, RENDER_FADE_INOUT, RENDER_END };

	enum COLLTYPE		{ COL_FALSE, COL_TRUE, COL_END };
	enum MESHTYPE		{ TYPE_STATIC, TYPE_DYNAMIC, TYPE_NAVI };

	enum ANGLE			{ ANGLE_X, ANGLE_Y, ANGLE_Z, ANGLE_END };
	enum MOUSEKEYSTATE	{ DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };


	// Object
	// StaticMesh
	enum class STATICMESH_TYPE : int
	{
		STATIC,
		DESTROY,
		SWITCH_FLOOR,
		CONVEYOR,
		GLASS_DOOR,
		BALL,
		CHECKPOINT,
		MAZE,
		ITEM,
		WARPPOINT,
		BASIC_DOOR,
		NEXT_STAGE_POINT,
		UPGRADE_POINT,
		LASER_FIXED,
		BOSS_COLUMN,
		WALL_LIGHT,
		WALL_LIGHT_SWITCH,
		SPAWNER
	};
}